const optimizeRecovery =
    require("./recoveryOptimizer");

const evaluateRecoveryPolicy =
    require("./recoveryPolicy");

const executeRecovery =
    require("./recoveryExecutor");

const createAuditLog =
    require("./auditLogger");


async function runRecoveryWorkflow({
    paymentId,
    payment,
    recommendation: providedRecommendation,
    incident
}) {

    /*
     * STEP 1
     * Use the existing AI recommendation if one was
     * already generated by the analysis step.
     *
     * Otherwise generate a new recommendation.
     */

    const recommendation =
        providedRecommendation ||
        await optimizeRecovery(
            payment
        );


    /*
     * STEP 2
     * Record optimization decision
     */

    await createAuditLog({

        eventType:
            "RECOVERY_OPTIMIZED",

        paymentId,

        merchantId:
            payment.merchantId || null,

        incidentId:
            incident?.incidentId || null,

        action:
            recommendation.recommendedAction,

        amount:
            payment.amount,

        recoveryProbability:
            recommendation.recoveryProbability ||
            null,

        expectedRecovery:
            recommendation.expectedRecovery ||
            null,

        expectedNetRecovery:
            recommendation.expectedNetRecovery ||
            null,

        status:
            "optimized",

        details: {

            reason:
                recommendation.reason,

            candidates:
                recommendation.candidates

        }

    });


    /*
     * STEP 3
     * Apply safety policy
     */

    const policy =
        evaluateRecoveryPolicy({

            payment: {

                ...payment,

                autoRecoveryAttempts:
                    payment.autoRecoveryAttempts || 0,

                retryCount:
                    payment.retryCount || 0

            },

            recommendation,

            incident

        });


    /*
     * STEP 4
     * Record policy decision
     */

    await createAuditLog({

        eventType:
            policy.allowed
                ? "RECOVERY_APPROVED"
                : "RECOVERY_BLOCKED",

        paymentId,

        merchantId:
            payment.merchantId || null,

        incidentId:
            incident?.incidentId || null,

        action:
            recommendation.recommendedAction ||
            null,

        amount:
            payment.amount,

        recoveryProbability:
            recommendation.recoveryProbability ||
            null,

        expectedRecovery:
            recommendation.expectedRecovery ||
            null,

        expectedNetRecovery:
            recommendation.expectedNetRecovery ||
            null,

        status:
            policy.decision,

        details: {

            reasons:
                policy.reasons,

            policy:
                policy.policy

        }

    });


    /*
     * STEP 5
     * Stop if policy blocks recovery
     */

    if (!policy.allowed) {

        return {

            paymentId,

            status:
                "blocked",

            recommendation,

            policy,

            execution:
                null

        };

    }


    /*
     * STEP 6
     * Execute recovery
     */

    const execution =
        await executeRecovery(
            paymentId,
            recommendation.recommendedAction
        );


    /*
     * STEP 7
     * Record execution
     */

    await createAuditLog({

        eventType:
            "RECOVERY_EXECUTED",

        paymentId,

        merchantId:
            payment.merchantId || null,

        incidentId:
            incident?.incidentId || null,

        action:
            recommendation.recommendedAction,

        amount:
            payment.amount,

        amountRecovered:
            execution.amountRecovered || 0,

        recoveryProbability:
            recommendation.recoveryProbability ||
            null,

        expectedRecovery:
            recommendation.expectedRecovery ||
            null,

        expectedNetRecovery:
            recommendation.expectedNetRecovery ||
            null,

        status:
            execution.status,

        details: {

            recoveryAttempt:
                execution.recoveryAttempt || null,

            message:
                execution.message || null,

            executedAt:
                execution.executedAt || null

        }

    });


    /*
     * STEP 8
     * Record final outcome
     */

    await createAuditLog({

        eventType:
            execution.success
                ? "RECOVERY_SUCCEEDED"
                : "RECOVERY_FAILED",

        paymentId,

        merchantId:
            payment.merchantId || null,

        incidentId:
            incident?.incidentId || null,

        action:
            recommendation.recommendedAction,

        amount:
            payment.amount,

        amountRecovered:
            execution.amountRecovered || 0,

        recoveryProbability:
            recommendation.recoveryProbability ||
            null,

        expectedRecovery:
            recommendation.expectedRecovery ||
            null,

        expectedNetRecovery:
            recommendation.expectedNetRecovery ||
            null,

        status:
            execution.status,

        details: {

            recoveryAttempt:
                execution.recoveryAttempt || null,

            message:
                execution.message || null

        }

    });


    /*
     * STEP 9
     * Return complete workflow
     */

    return {

        paymentId,

        status:
            execution.success
                ? "recovered"
                : "execution_failed",

        recommendation,

        policy,

        execution

    };

}


module.exports =
    runRecoveryWorkflow;